APP_NAME: mitsukeru-server
PORT: 14045
ENVIRONMENT: development
VERSION: 0.0.1

DB_TYPE: postgres
DB_LINK: 127.0.0.1
DB_PORT: 5431
DB_USER: howling-user
DB_PASS: VERYSECRETFORMULA
DB_NAME: howling-db
