version: '3'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/psql_init.sql:/docker-entrypoint-initdb.d/psql_init.sql
    environment:
      - POSTGRES_PASSWORD=VERYSECRETFORMULA
      - POSTGRES_USER=howling-user
      - POSTGRES_DB=howling-db
volumes:
  pgdata: